version: '3.8'

services:
  bet_maker:
    build:
      context: .
      dockerfile: bet_maker.Dockerfile
    container_name: bet_maker
    hostname: bet_maker
    ports:
      - "8000:8000"
    volumes:
      - ./bet_maker:/app/bet_maker
    networks:
      - app_network
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      postgres_bet_maker:
        condition: service_healthy
      line_provider:
        condition: service_healthy

  line_provider:
    build:
      context: .
      dockerfile: line_provider.Dockerfile
    container_name: line_provider
    hostname: line_provider
    ports:
      - "8080:8080"
    volumes:
      - ./line_provider:/app/line_provider
    networks:
      - app_network
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      postgres_line_provider:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  postgres_bet_maker:
    image: postgres:15-alpine
    container_name: postgres_bet_maker
    hostname: database_bet_maker
    environment:
      POSTGRES_USER: betting_app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: betting_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_bet_maker_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U betting_app_user -d betting_app"]
      interval: 5s
      timeout: 3s
      retries: 3

  postgres_line_provider:
    image: postgres:15-alpine
    container_name: postgres_line_provider
    hostname: database_line_provider
    environment:
      POSTGRES_USER: line_provider_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: line_provider
    ports:
      - "5433:5432"
    volumes:
      - postgres_line_provider_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U line_provider_user -d line_provider" ]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
  postgres_bet_maker_data:
  postgres_line_provider_data:

networks:
  app_network:
    driver: bridge
