"""event table

Revision ID: a68a22ace586
Revises:
Create Date: 2025-04-14 03:45:26.354348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a68a22ace586"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "state",
            sa.Enum("IN_PROGRESS", "FIRST_WIN", "SECOND_WIN", name="eventstate"),
            nullable=False,
        ),
        sa.Column("coefficient", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("deadline", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    # ### end Alembic commands ###
