[tool.poetry]
name = "bet-maker"
version = "0.1.0"
description = "Small API implemnetation for betting service"
authors = ["mur4d1n <mur4d1n@yandex.ru>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
alembic = "1.15.2"
asyncpg = "0.30.0"
fastapi = "0.115.12"
httpx = "0.28.1"
pydantic = "2.11.3"
redis = "5.2.1"
sqlalchemy = "2.0.40"
uvicorn = "0.34.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
